### ISSUE TITLE
content redundancy between data wrangling, and functional programming

### ISSUE THREAD

**Issue by emiliehenderson** [DHS-OEDA/Intro_R#4]
The material I have under baseR data wrangling details the apply, and lapply functions, as I often use them to churn through data summaries.

In some ways, a better home for this discussion is in functional programming, right after you introduce loops.

Any thoughts?

**Comment by DHS-OEDA** [comment]
I think it's good to introduce the apply functions in section 2 and then just mention them in section 4. They are important enough to learn early and if we keep them in section 2 we can be pretty certain the class will cover it.
